export const SIMPLE_ACTION = 'REACT_REDUX_STATERT_KIT/HOME/SIMPLE_ACTION';
export const GET_CHARACTER_DATA = 'REACT_REDUX_STATERT_KIT/HOME/GET_CHARACTER_DATA';
export const GET_CHARACTER_DATA_SUCCESS = 'REACT_REDUX_STATERT_KIT/HOME/GET_CHARACTER_DATA_SUCCESS';
export const GET_CHARACTER_DATA_FAIL = 'REACT_REDUX_STATERT_KIT/HOME/GET_CHARACTER_DATA_FAIL';
